package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.time.LocalDate;
import java.util.*;
@SpringBootApplication
public class DemoApplication {
	public static void main(String[] args) {
//		Fruit f =new Fruit();
//		Scanner sc=new Scanner(System.in);
//		System.out.print("Enter a fruit:");
//		String s =sc.nextLine();
//		f.fruitcase(s);
//		SpringApplication.run(DemoApplication.class, args);
		MusicPlayer musicplayer1=new MusicPlayer();
		musicplayer1.AddSong("Shape of You", "Ed Sheeran");
		musicplayer1.AddSong("Blinding Lights");
		musicplayer1.AddSong("Rolling in the Deep", "Adele");
		musicplayer1.AddSong("Lose Yourself");
		musicplayer1.AddSong("Thinking Out Loud", "Ed Sheeran");
		musicplayer1.AddSong("Someone Like You", "Adele");
		musicplayer1.AddSong("Perfect", "Ed Sheeran");
		musicplayer1.AddSong("Hello", "Adele");
		musicplayer1.AddSong("Havana", "Camila Cabello");
		musicplayer1.AddSong("Senorita", "Shawn Mendes");
		musicplayer1.AddSong("Shallow", "Lady Gaga");
		musicplayer1.AddSong("Bad Guy", "Billie Eilish");
		musicplayer1.AddSong("Sunflower", "Post Malone");
		musicplayer1.AddSong("Old Town Road");
		musicplayer1.AddSong("Believer", "Imagine Dragons");
		musicplayer1.AddSong("Radioactive", "Imagine Dragons");
		musicplayer1.AddSong("Closer", "The Chainsmokers");
		musicplayer1.AddSong("Stay", "The Kid LAROI");
		musicplayer1.AddSong("Levitating", "Dua Lipa");
		musicplayer1.AddSong("Circles", "Post Malone");
		musicplayer1.AddSong("Memories", "Maroon 5");
		musicplayer1.AddSong("Sugar", "Maroon 5");
		musicplayer1.AddSong("Girls Like You", "Maroon 5");
		musicplayer1.AddSong("Attention", "Charlie Puth");
		musicplayer1.AddSong("We Don't Talk Anymore", "Charlie Puth");
		musicplayer1.AddSong("See You Again", "Wiz Khalifa");
		musicplayer1.AddSong("Uptown Funk", "Mark Ronson");
		musicplayer1.AddSong("All of Me", "John Legend");
		musicplayer1.AddSong("Faded", "Alan Walker");
		musicplayer1.AddSong("Alone", "Alan Walker");
		musicplayer1.AddSong("Darkside", "Alan Walker");
		musicplayer1.AddSong("Friends", "Anne-Marie");
		musicplayer1.AddSong("Rockabye", "Clean Bandit");
		musicplayer1.AddSong("Symphony", "Clean Bandit");
		musicplayer1.AddSong("Titanium", "David Guetta");
		musicplayer1.AddSong("Don't Let Me Down", "The Chainsmokers");
		musicplayer1.AddSong("Something Just Like This", "The Chainsmokers");
		musicplayer1.AddSong("Waka Waka", "Shakira");
		musicplayer1.AddSong("Hips Don't Lie", "Shakira");
		musicplayer1.AddSong("Whenever, Wherever", "Shakira");
		musicplayer1.AddSong("Dance Monkey", "Tones and I");
		musicplayer1.AddSong("Savage Love", "Jason Derulo");
		musicplayer1.AddSong("Love Yourself", "Justin Bieber");
		musicplayer1.AddSong("Sorry", "Justin Bieber");
		musicplayer1.AddSong("Baby", "Justin Bieber");
		musicplayer1.AddSong("What Do You Mean", "Justin Bieber");
		musicplayer1.AddSong("Yummy", "Justin Bieber");
		musicplayer1.AddSong("Peaches", "Justin Bieber");
		musicplayer1.AddSong("Intentions", "Justin Bieber");
		musicplayer1.AddSong("No Tears Left to Cry", "Ariana Grande");
		musicplayer1.AddSong("Thank U, Next", "Ariana Grande");


		//play songs

		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Lose Yourself");
		musicplayer1.playsong("Thinking Out Loud");
		musicplayer1.playsong("Someone Like You");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Havana");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Bad Guy");
		musicplayer1.playsong("Sunflower");
		musicplayer1.playsong("Old Town Road");
		musicplayer1.playsong("Believer");
		musicplayer1.playsong("Radioactive");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Levitating");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Sugar");
		musicplayer1.playsong("Girls Like You");
		musicplayer1.playsong("Attention");
		musicplayer1.playsong("We Don't Talk Anymore");
		musicplayer1.playsong("See You Again");
		musicplayer1.playsong("Uptown Funk");
		musicplayer1.playsong("All of Me");
		musicplayer1.playsong("Faded");
		musicplayer1.playsong("Alone");
		musicplayer1.playsong("Darkside");
		musicplayer1.playsong("Friends");
		musicplayer1.playsong("Rockabye");
		musicplayer1.playsong("Symphony");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("Don't Let Me Down");
		musicplayer1.playsong("Something Just Like This");
		musicplayer1.playsong("Waka Waka");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Whenever, Wherever");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Savage Love");
		musicplayer1.playsong("Love Yourself");
		musicplayer1.playsong("Sorry");
		musicplayer1.playsong("Baby");
		musicplayer1.playsong("What Do You Mean");
		musicplayer1.playsong("Yummy");
		musicplayer1.playsong("Peaches");
		musicplayer1.playsong("Intentions");
		musicplayer1.playsong("No Tears Left to Cry");
		musicplayer1.playsong("Thank U, Next");
		musicplayer1.playsong("Side to Side");
		musicplayer1.playsong("Into You");
		musicplayer1.playsong("7 rings");
		musicplayer1.playsong("Break Free");
		musicplayer1.playsong("Bang Bang");
		musicplayer1.playsong("God is a Woman");
		musicplayer1.playsong("Positions");
		musicplayer1.playsong("Problem");
		musicplayer1.playsong("Stuck with U");
		musicplayer1.playsong("Imagine");
		musicplayer1.playsong("No Tears Left to Cry");
		musicplayer1.playsong("Save Your Tears");
		musicplayer1.playsong("In Your Eyes");
		musicplayer1.playsong("After Hours");
		musicplayer1.playsong("Call Out My Name");
		musicplayer1.playsong("Starboy");
		musicplayer1.playsong("The Hills");
		musicplayer1.playsong("I Feel It Coming");
		musicplayer1.playsong("Earned It");
		musicplayer1.playsong("Can't Feel My Face");
		musicplayer1.playsong("Pray for Me");
		musicplayer1.playsong("Heartless");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Take My Breath");
		musicplayer1.playsong("Die for You");
		musicplayer1.playsong("Out of Time");
		musicplayer1.playsong("Sacrifice");
		musicplayer1.playsong("Gasoline");
		musicplayer1.playsong("Is There Someone Else?");
		musicplayer1.playsong("Dawn FM");
		musicplayer1.playsong("Here We Go... Again");
		musicplayer1.playsong("Phantom Regret by Jim");
		musicplayer1.playsong("True Colors");
		musicplayer1.playsong("Remedy");
		musicplayer1.playsong("Lay Me Down");
		musicplayer1.playsong("Stay With Me");
		musicplayer1.playsong("Too Good at Goodbyes");
		musicplayer1.playsong("I'm Not the Only One");
		musicplayer1.playsong("Like I Can");
		musicplayer1.playsong("Writing's on the Wall");
		musicplayer1.playsong("Dancing with a Stranger");
		musicplayer1.playsong("How Do You Sleep?");
		musicplayer1.playsong("Fire on Fire");
		musicplayer1.playsong("To Die For");
		musicplayer1.playsong("Diamonds");
		musicplayer1.playsong("Love Goes");
		musicplayer1.playsong("Forgive Myself");
		musicplayer1.playsong("Another One");
		musicplayer1.playsong("Breaking Hearts");
		musicplayer1.playsong("Young");
		musicplayer1.playsong("Him");
		musicplayer1.playsong("Midnight Train");
		musicplayer1.playsong("Younger Now");
		musicplayer1.playsong("Malibu");
		musicplayer1.playsong("Adore You");
		musicplayer1.playsong("Mother's Daughter");
		musicplayer1.playsong("Nothing Breaks Like a Heart");
		musicplayer1.playsong("Prisoner");
		musicplayer1.playsong("Plastic Hearts");
		musicplayer1.playsong("Wrecking Ball");
		musicplayer1.playsong("We Can't Stop");
		musicplayer1.playsong("Party in the USA");
		musicplayer1.playsong("The Climb");
		musicplayer1.playsong("Fly on the Wall");
		musicplayer1.playsong("When I Look at You");
		musicplayer1.playsong("Can't Be Tamed");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Run");
		musicplayer1.playsong("Wake Me Up");
		musicplayer1.playsong("Fade Into Darkness");
		musicplayer1.playsong("Silhouettes");
		musicplayer1.playsong("The Nights");
		musicplayer1.playsong("Levels");
		musicplayer1.playsong("Addicted to You");
		musicplayer1.playsong("For a Better Day");
		musicplayer1.playsong("Without You");
		musicplayer1.playsong("Heaven");
		musicplayer1.playsong("SOS");
		musicplayer1.playsong("Tough Love");
		musicplayer1.playsong("Peace of Mind");
		musicplayer1.playsong("Bad Reputation");
		musicplayer1.playsong("Excuse Me Mr. Sir");
		musicplayer1.playsong("With A Smile");
		musicplayer1.playsong("Rainbow");
		musicplayer1.playsong("Your Universe");
		musicplayer1.playsong("Narda");
		musicplayer1.playsong("Banal na Aso");
		musicplayer1.playsong("Eraserheads");
		musicplayer1.playsong("Hallelujah");
		musicplayer1.playsong("Time and Space");
		musicplayer1.playsong("Ang Huling El Bimbo");
		musicplayer1.playsong("Pag-Ibig");
		musicplayer1.playsong("Jeepney");
		musicplayer1.playsong("Elisi");
		musicplayer1.playsong("With Love");
		musicplayer1.playsong("Until Now");
		musicplayer1.playsong("Superstar");
		musicplayer1.playsong("Dahil Minahal Mo Ako");
		musicplayer1.playsong("Huwag Ka Nang Umiyak");
		musicplayer1.playsong("Tadhana");
		musicplayer1.playsong("Upuan");
		musicplayer1.playsong("Walang Hanggan");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Lose Yourself");
		musicplayer1.playsong("Thinking Out Loud");
		musicplayer1.playsong("Someone Like You");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Havana");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Sunflower");
		musicplayer1.playsong("Old Town Road");
		musicplayer1.playsong("Believer");
		musicplayer1.playsong("Radioactive");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Levitating");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Girls Like You");
		musicplayer1.playsong("Attention");
		musicplayer1.playsong("We Don't Talk Anymore");
		musicplayer1.playsong("We Don't Talk Anymore");
		musicplayer1.playsong("Attention");
		musicplayer1.playsong("See You Again");
		musicplayer1.playsong("Uptown Funk");
		musicplayer1.playsong("All of Me");
		musicplayer1.playsong("Faded");
		musicplayer1.playsong("Alone");
		musicplayer1.playsong("Darkside");
		musicplayer1.playsong("Friends");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Rockabye");
		musicplayer1.playsong("Symphony");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("Don't Let Me Down");
		musicplayer1.playsong("Something Just Like This");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Whenever, Wherever");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Savage Love");
		musicplayer1.playsong("Love Yourself");
		musicplayer1.playsong("Sorry");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Baby");
		musicplayer1.playsong("What Do You Mean");
		musicplayer1.playsong("Yummy");
		musicplayer1.playsong("Peaches");
		musicplayer1.playsong("Intentions");
		musicplayer1.playsong("No Tears Left to Cry");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Save Your Tears");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Old Town Road");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Uptown Funk");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Darkside");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("We Don't Talk Anymore");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Believer");
		musicplayer1.playsong("Radioactive");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Girls Like You");
		musicplayer1.playsong("All of Me");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Savage Love");
		musicplayer1.playsong("Love Yourself");
		musicplayer1.playsong("Sorry");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Intentions");
		musicplayer1.playsong("Thank U, Next");
		musicplayer1.playsong("Faded");
		musicplayer1.playsong("Alone");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Sunflower");
		musicplayer1.playsong("No Tears Left to Cry");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("All of Me");
		musicplayer1.playsong("Girls Like You");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Symphony");
		musicplayer1.playsong("Symphony");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("No Tears Left to Cry");
		musicplayer1.playsong("Waka Waka");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Sugar");
		musicplayer1.playsong("Faded");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Havana");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Symphony");
		musicplayer1.playsong("Believer");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Old Town Road");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Darkside");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Old Town Road");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Believer");
		musicplayer1.playsong("Radioactive");
		musicplayer1.playsong("Havana");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Lose Yourself");
		musicplayer1.playsong("Thinking Out Loud");
		musicplayer1.playsong("Someone Like You");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Havana");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Sunflower");
		musicplayer1.playsong("Old Town Road");
		musicplayer1.playsong("Believer");
		musicplayer1.playsong("Radioactive");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Levitating");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Girls Like You");
		musicplayer1.playsong("Attention");
		musicplayer1.playsong("We Don't Talk Anymore");
		musicplayer1.playsong("We Don't Talk Anymore");
		musicplayer1.playsong("Attention");
		musicplayer1.playsong("See You Again");
		musicplayer1.playsong("Uptown Funk");
		musicplayer1.playsong("All of Me");
		musicplayer1.playsong("Faded");
		musicplayer1.playsong("Alone");
		musicplayer1.playsong("Darkside");
		musicplayer1.playsong("Friends");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Rockabye");
		musicplayer1.playsong("Symphony");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("Don't Let Me Down");
		musicplayer1.playsong("Something Just Like This");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Whenever, Wherever");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Savage Love");
		musicplayer1.playsong("Love Yourself");
		musicplayer1.playsong("Sorry");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Baby");
		musicplayer1.playsong("What Do You Mean");
		musicplayer1.playsong("Yummy");
		musicplayer1.playsong("Peaches");
		musicplayer1.playsong("Intentions");
		musicplayer1.playsong("No Tears Left to Cry");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Save Your Tears");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Old Town Road");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Uptown Funk");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Darkside");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("We Don't Talk Anymore");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Believer");
		musicplayer1.playsong("Radioactive");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Girls Like You");
		musicplayer1.playsong("All of Me");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Savage Love");
		musicplayer1.playsong("Love Yourself");
		musicplayer1.playsong("Sorry");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Intentions");
		musicplayer1.playsong("Thank U, Next");
		musicplayer1.playsong("Faded");
		musicplayer1.playsong("Alone");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Sunflower");
		musicplayer1.playsong("No Tears Left to Cry");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("All of Me");
		musicplayer1.playsong("Girls Like You");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Symphony");
		musicplayer1.playsong("Symphony");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("No Tears Left to Cry");
		musicplayer1.playsong("Waka Waka");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Sugar");
		musicplayer1.playsong("Faded");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Havana");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Symphony");
		musicplayer1.playsong("Believer");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Old Town Road");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Darkside");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Old Town Road");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Believer");
		musicplayer1.playsong("Radioactive");
		musicplayer1.playsong("Havana");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("Stay");




		//now getting top songs
		System.out.println("Following is the list of top 10 songs by Post Malone");
		musicplayer1.gettop10songbyartist("Post Malone");
		System.out.println("\n\n");
		System.out.println("Following is the list of top 10 songs by Shakira");
		musicplayer1.gettop10songbyartist("Shakira");
		System.out.println("\n\n");
		System.out.println("Following is the list of top 10 songs");
		musicplayer1.gettop10song();
		System.out.println("\n\n");
		System.out.println("All songs by Ed sheeran ");
		musicplayer1.retrivesong("Ed Sheeran");
		System.out.println("\n\n");
		LocalDate d=LocalDate.now();
		System.out.println("Top 10 song "+d+" are");
		musicplayer1.gettop10songbydate(d);
		System.out.println("\n\n");


		musicplayer1.GotoNextDay();
		musicplayer1.playsong("Lose Yourself");
		musicplayer1.playsong("Thinking Out Loud");
		musicplayer1.playsong("Someone Like You");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Havana");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Sunflower");
		musicplayer1.playsong("Old Town Road");
		musicplayer1.playsong("Believer");
		musicplayer1.playsong("Radioactive");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Levitating");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Girls Like You");
		musicplayer1.playsong("Attention");
		musicplayer1.playsong("We Don't Talk Anymore");
		musicplayer1.playsong("We Don't Talk Anymore");
		musicplayer1.playsong("Attention");
		musicplayer1.playsong("See You Again");
		musicplayer1.playsong("Uptown Funk");
		musicplayer1.playsong("All of Me");
		musicplayer1.playsong("Faded");
		musicplayer1.playsong("Alone");
		musicplayer1.playsong("Darkside");
		musicplayer1.playsong("Friends");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Rockabye");
		musicplayer1.playsong("Symphony");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("Don't Let Me Down");
		musicplayer1.playsong("Something Just Like This");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Whenever, Wherever");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Savage Love");
		musicplayer1.playsong("Love Yourself");
		musicplayer1.playsong("Sorry");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Baby");
		musicplayer1.playsong("What Do You Mean");
		musicplayer1.playsong("Yummy");
		musicplayer1.playsong("Peaches");
		musicplayer1.playsong("Intentions");
		musicplayer1.playsong("No Tears Left to Cry");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Save Your Tears");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Old Town Road");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Uptown Funk");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Darkside");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("We Don't Talk Anymore");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Believer");
		musicplayer1.playsong("Radioactive");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Girls Like You");
		musicplayer1.playsong("All of Me");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Savage Love");
		musicplayer1.playsong("Love Yourself");
		musicplayer1.playsong("Sorry");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Intentions");
		musicplayer1.playsong("Thank U, Next");
		musicplayer1.playsong("Faded");
		musicplayer1.playsong("Alone");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Sunflower");
		musicplayer1.playsong("No Tears Left to Cry");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("All of Me");
		musicplayer1.playsong("Girls Like You");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Symphony");
		musicplayer1.playsong("Symphony");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("No Tears Left to Cry");
		musicplayer1.playsong("Waka Waka");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Sugar");
		musicplayer1.playsong("Faded");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Havana");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Symphony");
		musicplayer1.playsong("Believer");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Old Town Road");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Darkside");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Old Town Road");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Believer");
		musicplayer1.playsong("Radioactive");
		musicplayer1.playsong("Havana");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Lose Yourself");
		musicplayer1.playsong("Thinking Out Loud");
		musicplayer1.playsong("Someone Like You");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Havana");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Sunflower");
		musicplayer1.playsong("Old Town Road");
		musicplayer1.playsong("Believer");
		musicplayer1.playsong("Radioactive");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Levitating");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Girls Like You");
		musicplayer1.playsong("Attention");
		musicplayer1.playsong("We Don't Talk Anymore");
		musicplayer1.playsong("We Don't Talk Anymore");
		musicplayer1.playsong("Attention");
		musicplayer1.playsong("See You Again");
		musicplayer1.playsong("Uptown Funk");
		musicplayer1.playsong("All of Me");
		musicplayer1.playsong("Faded");
		musicplayer1.playsong("Alone");
		musicplayer1.playsong("Darkside");
		musicplayer1.playsong("Friends");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Rockabye");
		musicplayer1.playsong("Symphony");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("Don't Let Me Down");
		musicplayer1.playsong("Something Just Like This");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Whenever, Wherever");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Savage Love");
		musicplayer1.playsong("Love Yourself");
		musicplayer1.playsong("Sorry");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Baby");
		musicplayer1.playsong("What Do You Mean");
		musicplayer1.playsong("Yummy");
		musicplayer1.playsong("Peaches");
		musicplayer1.playsong("Intentions");
		musicplayer1.playsong("No Tears Left to Cry");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Save Your Tears");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Old Town Road");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Uptown Funk");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Darkside");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("We Don't Talk Anymore");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Believer");
		musicplayer1.playsong("Radioactive");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Girls Like You");
		musicplayer1.playsong("All of Me");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Savage Love");
		musicplayer1.playsong("Love Yourself");
		musicplayer1.playsong("Sorry");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Intentions");
		musicplayer1.playsong("Thank U, Next");
		musicplayer1.playsong("Faded");
		musicplayer1.playsong("Alone");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Sunflower");
		musicplayer1.playsong("No Tears Left to Cry");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Perfect");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("All of Me");
		musicplayer1.playsong("Girls Like You");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Symphony");
		musicplayer1.playsong("Symphony");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("No Tears Left to Cry");
		musicplayer1.playsong("Waka Waka");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Sugar");
		musicplayer1.playsong("Faded");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Havana");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Symphony");
		musicplayer1.playsong("Believer");
		musicplayer1.playsong("Shape of You");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Old Town Road");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Darkside");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Shallow");
		musicplayer1.playsong("Circles");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Dance Monkey");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Old Town Road");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Stay");
		musicplayer1.playsong("Believer");
		musicplayer1.playsong("Radioactive");
		musicplayer1.playsong("Havana");
		musicplayer1.playsong("Senorita");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Hips Don't Lie");
		musicplayer1.playsong("Hello");
		musicplayer1.playsong("Rolling in the Deep");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Memories");
		musicplayer1.playsong("Closer");
		musicplayer1.playsong("Blinding Lights");
		musicplayer1.playsong("Titanium");
		musicplayer1.playsong("Stay");
		d=d.plusDays(1);
		System.out.println("Top 10 song " + d + " are");
		musicplayer1.gettop10songbydate(d);
	}
}
